// <auto-generated />
namespace ElectronicsStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ElectronicsStore_StoreContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ElectronicsStore_StoreContext));
        
        string IMigrationMetadata.Id
        {
            get { return "201712082020440_ElectronicsStore_StoreContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
